# Generated by Django 5.2.4 on 2025-09-21 23:10

import movie.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movie', '0009_alter_movie_emb'),
    ]

    operations = [
        migrations.AlterField(
            model_name='movie',
            name='emb',
            field=models.BinaryField(default=movie.models.get_default_array),
        ),
        migrations.AlterField(
            model_name='movie',
            name='image',
            field=models.ImageField(default='movie/images/sin_image.jpg', upload_to='movie/images/'),
        ),
    ]
